// Generated by CoffeeScript 1.3.1
var args, fireEvent, isAuthorized, login, logout, request, twitter;

args = arguments[0] || {};

twitter = require('jp.coe.mod.twitter').Twitter({
  consumerKey: "",
  consumerSecret: "",
  accessTokenKey: Ti.App.Properties.getString('twitterAccessTokenKey', ''),
  accessTokenSecret: Ti.App.Properties.getString('twitterAccessTokenSecret', '')
});

twitter.addEventListener("login", function(e) {
  return alert("login");
});

login = function() {
  return twitter.authorize();
};

logout = function() {
  return twitter.logout(function() {
    return alert("logout");
  });
};

request = function() {
  return twitter.request();
};

fireEvent = function() {};

isAuthorized = function() {
  return twitter.isAuthorized();
};
